// Generated by gencpp from file sounddevice_ros/AudioInfo.msg
// DO NOT EDIT!


#ifndef SOUNDDEVICE_ROS_MESSAGE_AUDIOINFO_H
#define SOUNDDEVICE_ROS_MESSAGE_AUDIOINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sounddevice_ros
{
template <class ContainerAllocator>
struct AudioInfo_
{
  typedef AudioInfo_<ContainerAllocator> Type;

  AudioInfo_()
    : header()
    , num_channels(0)
    , sample_rate(0)
    , subtype()  {
    }
  AudioInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_channels(0)
    , sample_rate(0)
    , subtype(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _num_channels_type;
  _num_channels_type num_channels;

   typedef int32_t _sample_rate_type;
  _sample_rate_type sample_rate;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subtype_type;
  _subtype_type subtype;





  typedef boost::shared_ptr< ::sounddevice_ros::AudioInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sounddevice_ros::AudioInfo_<ContainerAllocator> const> ConstPtr;

}; // struct AudioInfo_

typedef ::sounddevice_ros::AudioInfo_<std::allocator<void> > AudioInfo;

typedef boost::shared_ptr< ::sounddevice_ros::AudioInfo > AudioInfoPtr;
typedef boost::shared_ptr< ::sounddevice_ros::AudioInfo const> AudioInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sounddevice_ros::AudioInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sounddevice_ros::AudioInfo_<ContainerAllocator1> & lhs, const ::sounddevice_ros::AudioInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.num_channels == rhs.num_channels &&
    lhs.sample_rate == rhs.sample_rate &&
    lhs.subtype == rhs.subtype;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sounddevice_ros::AudioInfo_<ContainerAllocator1> & lhs, const ::sounddevice_ros::AudioInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sounddevice_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sounddevice_ros::AudioInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sounddevice_ros::AudioInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sounddevice_ros::AudioInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d52fdd030548864e37e9bab9114e6549";
  }

  static const char* value(const ::sounddevice_ros::AudioInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd52fdd030548864eULL;
  static const uint64_t static_value2 = 0x37e9bab9114e6549ULL;
};

template<class ContainerAllocator>
struct DataType< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sounddevice_ros/AudioInfo";
  }

  static const char* value(const ::sounddevice_ros::AudioInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 num_channels\n"
"int32 sample_rate\n"
"string subtype\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sounddevice_ros::AudioInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_channels);
      stream.next(m.sample_rate);
      stream.next(m.subtype);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sounddevice_ros::AudioInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sounddevice_ros::AudioInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_channels: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_channels);
    s << indent << "sample_rate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sample_rate);
    s << indent << "subtype: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subtype);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOUNDDEVICE_ROS_MESSAGE_AUDIOINFO_H
